package com.mycompany.projet_java;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.Timer;


public class assuranceNouvelle extends javax.swing.JFrame {

private Connection connection = null;

Timer t = new Timer(0, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
        
        java.util.Date dt  =new java.util.Date();
        SimpleDateFormat st = new SimpleDateFormat("h:mm:ss a");        
        String tt = st.format(dt);
        labelHeure.setText(tt);
        
        
        double RCM;
        int c = cboCategorie.getSelectedIndex();
        if (c == 0) {
            double RC = 41160;// RC= prime nette(51452) *80% pour Catégorie 1
            
            txtRC.setText(Double.toString(RC));
            RCM = RC * 0.0875 * Double.valueOf(nombreMois.getValue());
            txtPrimeNette.setText(Double.toString(RCM));
            
            double fg = RCM * 0.025;
            txtFG.setText(Double.toString(fg));
            
            double taxe = RCM * 3000 * 0.1;
            txtTaxe.setText(Double.toString(taxe));
            
            double TTC = RCM + taxe + fg;
            txtPT.setText(Double.toString(TTC));
            
        } else  if (c == 3) {
            
            double RC2 = 48800;// RC= prime nette(61 000)  *80% pour Catégorie 4 
            txtRC.setText(Double.toString(RC2));
            RCM = RC2 * 0.0875 * Double.valueOf(nombreMois.getValue());
            txtPrimeNette.setText(Double.toString(RCM));
            
            double fg2 = RCM * 0.025;
            txtFG.setText(Double.toString(fg2));
            
            double taxe2 = RCM * 3000 * 0.1;
            txtTaxe.setText(Double.toString(taxe2));

            
            double TTC2 = RCM + taxe2 + fg2;
            txtPT.setText(Double.toString(TTC2));
        }
        
        }
});

    public assuranceNouvelle() {
        //this.ta = T;
        initComponents();
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cboTalon = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboGroupe = new javax.swing.JComboBox<>();
        txtAssure = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtProfession = new javax.swing.JTextField();
        txtVehicule = new javax.swing.JTextField();
        txtRC = new javax.swing.JTextField();
        txtMarque = new javax.swing.JTextField();
        txtImmat = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPT = new javax.swing.JTextField();
        dateRappel = new com.toedter.calendar.JDateChooser();
        dateDelivrance = new com.toedter.calendar.JDateChooser();
        nombreChevaux = new com.toedter.components.JSpinField();
        txtPolice = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtAdresse = new javax.swing.JTextField();
        cboTonnage = new javax.swing.JComboBox<>();
        txtTelephone = new javax.swing.JTextField();
        dateEcheance = new com.toedter.calendar.JDateChooser();
        nombreMois = new com.toedter.components.JSpinField();
        cboCategorie = new javax.swing.JComboBox<>();
        cboEnergie = new javax.swing.JComboBox<>();
        nombrePlaces = new com.toedter.components.JSpinField();
        txtCoutPolice = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtAttest = new javax.swing.JTextField();
        btnImprimer = new javax.swing.JButton();
        label12 = new javax.swing.JLabel();
        btnValider1 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        txtGenre = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        txtPrimeNette = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        txtTaxe = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        txtFG = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        txtSommeEncaisse = new javax.swing.JTextField();
        txtSommeFacture = new javax.swing.JTextField();
        btnValider = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        labelHeure = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnFermerAN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(assuranceNouvelle.MAXIMIZED_BOTH);
        setIconImages(null);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(204, 0, 51));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 808));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Date Rappel");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 110, -1));

        cboTalon.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        cboTalon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HORSPOOL TALON JAUNE", "POOL TALON VERT" }));
        cboTalon.setSelectedIndex(-1);
        cboTalon.setToolTipText("");
        cboTalon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboTalonMouseClicked(evt);
            }
        });
        cboTalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTalonActionPerformed(evt);
            }
        });
        jPanel1.add(cboTalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 210, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Type de producteur");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 128, 20));

        cboGroupe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argenciel", "Pole" }));
        cboGroupe.setSelectedIndex(-1);
        cboGroupe.setToolTipText("");
        cboGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGroupeActionPerformed(evt);
            }
        });
        jPanel1.add(cboGroupe, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 190, 30));

        txtAssure.setToolTipText("");
        txtAssure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssureActionPerformed(evt);
            }
        });
        jPanel1.add(txtAssure, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 212, 30));

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Attestation");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 69, 20));

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Immatriculation");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 100, 20));

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Police");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 69, -1));

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Marque");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 69, -1));

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Véhicule");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 69, -1));

        jLabel12.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Groupe");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 69, -1));

        jLabel13.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Telephone");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 69, -1));

        jLabel14.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Profession");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 69, -1));

        jLabel15.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Date échéance");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 90, -1));

        jLabel16.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Nombre de mois");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 110, -1));

        jLabel17.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Date délivrance");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 110, -1));

        txtProfession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessionActionPerformed(evt);
            }
        });
        jPanel1.add(txtProfession, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 212, 30));

        txtVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehiculeActionPerformed(evt);
            }
        });
        jPanel1.add(txtVehicule, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 212, 30));

        txtRC.setEditable(false);
        txtRC.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtRC.setForeground(new java.awt.Color(178, 17, 17));
        txtRC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 0, 0)));
        txtRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRCActionPerformed(evt);
            }
        });
        jPanel1.add(txtRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 212, 30));

        txtMarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarqueActionPerformed(evt);
            }
        });
        jPanel1.add(txtMarque, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 212, 30));

        txtImmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImmatActionPerformed(evt);
            }
        });
        jPanel1.add(txtImmat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 210, 30));

        jLabel18.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Genre");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 69, -1));

        txtPT.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        txtPT.setForeground(new java.awt.Color(178, 17, 17));
        txtPT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 0, 0)));
        txtPT.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPTActionPerformed(evt);
            }
        });
        jPanel1.add(txtPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 212, 30));

        dateRappel.setEnabled(false);
        jPanel1.add(dateRappel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 190, 30));
        jPanel1.add(dateDelivrance, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 190, 30));
        jPanel1.add(nombreChevaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 110, 60, -1));

        txtPolice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPoliceActionPerformed(evt);
            }
        });
        jPanel1.add(txtPolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 190, 30));

        jLabel20.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Categorie");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 69, -1));

        jLabel21.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Nombre de places");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, 120, -1));

        jLabel22.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Energie ");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 69, -1));

        jLabel24.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Tonnage");
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 100, -1));

        jLabel25.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Adresse");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 69, -1));

        txtAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdresseActionPerformed(evt);
            }
        });
        jPanel1.add(txtAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 212, 30));

        cboTonnage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+3.5 Tonnes", "-3.5 Tonnes" }));
        cboTonnage.setSelectedIndex(-1);
        jPanel1.add(cboTonnage, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 190, 30));

        txtTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 212, 30));

        dateEcheance.setEnabled(false);
        jPanel1.add(dateEcheance, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 190, 30));
        jPanel1.add(nombreMois, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 50, 60, -1));

        cboCategorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Catégorie 1: Particulier, Vehicule Utilitaire", "Catégorie 2: Camionette", "Catégorie 3: TPM-Transport Marchandise", "Catégorie 4: Bus Tata, Taxi" }));
        cboCategorie.setSelectedIndex(-1);
        cboCategorie.setAutoscrolls(true);
        jPanel1.add(cboCategorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 190, 30));

        cboEnergie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Essence", "Gazoile" }));
        cboEnergie.setSelectedIndex(-1);
        jPanel1.add(cboEnergie, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 190, 30));
        jPanel1.add(nombrePlaces, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 80, 60, -1));

        txtCoutPolice.setForeground(new java.awt.Color(204, 0, 0));
        txtCoutPolice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        txtCoutPolice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoutPoliceActionPerformed(evt);
            }
        });
        jPanel1.add(txtCoutPolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 190, 30));

        jLabel26.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("COUT DE POLICE");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 120, -1));

        jLabel27.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Responsabilité civile");
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 140, -1));

        jLabel28.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 30, -1));

        jLabel29.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 30, -1));

        jLabel30.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 30, -1));

        jLabel32.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 30, -1));

        jLabel33.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 30, -1));

        jLabel34.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 30, -1));

        jLabel35.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 30, -1));

        jLabel36.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 30, -1));

        jLabel37.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 30, -1));

        jLabel38.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 30, -1));

        jLabel39.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 30, -1));

        jLabel41.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 30, -1));

        jLabel42.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 30, -1));

        jLabel47.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Nombre de CV");
        jLabel47.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 100, -1));

        txtAttest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAttestActionPerformed(evt);
            }
        });
        jPanel1.add(txtAttest, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 190, 30));

        btnImprimer.setBackground(new java.awt.Color(255, 255, 255));
        btnImprimer.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnImprimer.setForeground(new java.awt.Color(102, 102, 102));
        btnImprimer.setText("Imprimer la carte grise");
        btnImprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImprimerMouseClicked(evt);
            }
        });
        btnImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimerActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, 290, -1));

        label12.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        label12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label12.setText("Consulter l'heure Actuelle");
        label12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 330, 230, 30));

        btnValider1.setBackground(new java.awt.Color(255, 50, 50));
        btnValider1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnValider1.setForeground(new java.awt.Color(255, 255, 255));
        btnValider1.setText("Calculer");
        btnValider1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValider1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnValider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 190, -1));

        jLabel50.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Nom Prénom Assuré");
        jLabel50.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 150, -1));

        txtGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenreActionPerformed(evt);
            }
        });
        jPanel1.add(txtGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 212, 30));

        jLabel51.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Prime Nette");
        jLabel51.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 140, -1));

        txtPrimeNette.setEditable(false);
        txtPrimeNette.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtPrimeNette.setForeground(new java.awt.Color(178, 17, 17));
        txtPrimeNette.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrimeNette.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 0, 0)));
        txtPrimeNette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimeNetteActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrimeNette, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 212, 30));

        jLabel52.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("Taxe");
        jLabel52.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 90, -1));

        txtTaxe.setEditable(false);
        txtTaxe.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtTaxe.setForeground(new java.awt.Color(178, 17, 17));
        txtTaxe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTaxe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 0, 0)));
        txtTaxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaxeActionPerformed(evt);
            }
        });
        jPanel1.add(txtTaxe, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 212, 30));

        jLabel53.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Fond de garantie");
        jLabel53.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 140, -1));

        txtFG.setEditable(false);
        txtFG.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtFG.setForeground(new java.awt.Color(178, 17, 17));
        txtFG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 0, 0)));
        txtFG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFGActionPerformed(evt);
            }
        });
        jPanel1.add(txtFG, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 212, 30));

        jLabel55.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("SOMME FACTUREE");
        jLabel55.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 130, -1));

        jLabel57.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(204, 0, 51));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("SOMME ENCAISSEE");
        jLabel57.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 140, 20));

        txtSommeEncaisse.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        txtSommeEncaisse.setForeground(new java.awt.Color(204, 0, 0));
        txtSommeEncaisse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSommeEncaisse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        txtSommeEncaisse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSommeEncaisseActionPerformed(evt);
            }
        });
        jPanel1.add(txtSommeEncaisse, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 190, 30));

        txtSommeFacture.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        txtSommeFacture.setForeground(new java.awt.Color(204, 0, 0));
        txtSommeFacture.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSommeFacture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        txtSommeFacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSommeFactureActionPerformed(evt);
            }
        });
        jPanel1.add(txtSommeFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 190, 30));

        btnValider.setBackground(new java.awt.Color(255, 50, 50));
        btnValider.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnValider.setForeground(new java.awt.Color(255, 255, 255));
        btnValider.setText("Enregistrer");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });
        jPanel1.add(btnValider, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, 290, 40));

        jLabel60.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 30, -1));

        jLabel61.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("PRIME TOTAL");
        jLabel61.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 180, 30));

        labelHeure.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        labelHeure.setForeground(new java.awt.Color(255, 51, 51));
        labelHeure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeure.setText("00:00:00");
        labelHeure.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(labelHeure, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 360, 170, 30));

        jLabel49.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 30, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 140, -1, 250));

        btnFermerAN.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnFermerAN.setText("Fermer");
        btnFermerAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFermerANMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFermerANMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFermerANMouseExited(evt);
            }
        });
        btnFermerAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerANActionPerformed(evt);
            }
        });
        jPanel1.add(btnFermerAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, 80, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\image Projet java\\téléchargement__1_-removebg-preview.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, 200, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(713, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setLocation(new java.awt.Point(0, 0));
    }// </editor-fold>//GEN-END:initComponents

    private void cboTalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTalonActionPerformed
    int n = cboTalon.getSelectedIndex();
    System.out.println("valeur de n index"+n);
        if(n==0){
            jPanel1.setBackground(Color.yellow);
        }else if(n==1){
            jPanel1.setBackground(Color.green);
        } 
    }//GEN-LAST:event_cboTalonActionPerformed

    private void cboGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGroupeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGroupeActionPerformed

    private void cboTalonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboTalonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTalonMouseClicked

    private void txtAssureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssureActionPerformed

    private void txtProfessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessionActionPerformed

    private void txtVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehiculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehiculeActionPerformed

    private void txtRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRCActionPerformed

    private void txtMarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarqueActionPerformed

    private void txtImmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImmatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImmatActionPerformed

    private void txtPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPTActionPerformed

    private void txtPoliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPoliceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPoliceActionPerformed

    private void txtAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdresseActionPerformed

    private void txtTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneActionPerformed

    private void txtCoutPoliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoutPoliceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoutPoliceActionPerformed

    private void txtAttestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAttestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAttestActionPerformed

    private void btnImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimerActionPerformed

    private void btnValider1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValider1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValider1ActionPerformed

    private void txtGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenreActionPerformed

    private void txtPrimeNetteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimeNetteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimeNetteActionPerformed

    private void txtTaxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaxeActionPerformed

    private void txtFGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFGActionPerformed

    private void txtSommeEncaisseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSommeEncaisseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSommeEncaisseActionPerformed

    private void txtSommeFactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSommeFactureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSommeFactureActionPerformed

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        try{ 
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/assurance", "root", ""); 
            String sql ="INSERT INTO `alldata`(`operateur`, `clientAssure`, `profession`, `adresse`, `telephone`, `dateEcheance`, `dateDelivrance`, `heure`, `prime_total`,`primeNette`, `nomCompagnie`, `marque`, `immatriculation`, `genre`, `puissanceMoteur`, `energie`, `nombrePlaces`, `nombreMois`, `talon`, `groupe`, `categorie`, `numeroPolice`, `attestation`, `tonnage`, `commission`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            int telephone = Integer.parseInt(txtTelephone.getText());
            
            SimpleDateFormat tdate = new SimpleDateFormat("yyyy-MM-dd");
            String dateEche = tdate.format(dateEcheance.getDate());
            String dateDeliv = tdate.format(dateDelivrance.getDate());
            
            java.util.Date date =new java.util.Date();
            java.sql.Date sqlDate =new java.sql.Date(date.getTime());
            java.sql.Timestamp sqlTime=new java.sql.Timestamp(date.getTime());
            
            String categorie = (String) cboCategorie.getSelectedItem();
            String energie = (String) cboEnergie.getSelectedItem();
            String tonnage = (String) cboTonnage.getSelectedItem();
            String groupe = (String) cboGroupe.getSelectedItem();
            String talon = (String) cboTalon.getSelectedItem();

            int police  = Integer.parseInt(txtPolice.getText());
            int attestation = Integer.parseInt(txtAttest.getText());
            
            try (PreparedStatement ptmt = connection.prepareStatement(sql)) {
                ptmt.setString(1, "MODOU NAR NONGO");
                ptmt.setString(2, txtAssure.getText());
                ptmt.setString(3, txtProfession.getText());
                ptmt.setString(4, txtAdresse.getText());
                ptmt.setInt(5, telephone);
                ptmt.setString(6,dateEche);
                ptmt.setString(7, dateDeliv);
                ptmt.setTimestamp(8, sqlTime);
                ptmt.setInt(9, 0); //----------- Prime Total à calculer !!!------------
                ptmt.setInt(10,0); //----------- Prime Nette à calculer !!!------------
                ptmt.setString(11, "ASSURANCE AUTOMOBILE Senegalaise");
                ptmt.setString(12,txtMarque.getText());
                ptmt.setString(13,txtImmat.getText());
                ptmt.setString(14,txtGenre.getText());
                ptmt.setInt(15, nombreChevaux.getValue());
                ptmt.setString(16, energie);
                ptmt.setInt(17, nombrePlaces.getValue());
                ptmt.setInt(18, nombreMois.getValue());
                ptmt.setString(19,talon);
                ptmt.setString(20, groupe);
                ptmt.setString(21,categorie);
                ptmt.setInt(22,police);
                ptmt.setInt(23,attestation);
                ptmt.setString(24, tonnage);
                ptmt.setInt(25,0); // -------COMMISSION A CALCULER --------

                ptmt.executeUpdate();
                //JOptionPane.showMessageDialog(null,"Informations de l'assuré ajoutées avec succés",null,JOptionPane.INFORMATION_MESSAGE);
                jTextArea1.setForeground(Color.green);
                jTextArea1.setText("Informations de l'assuré ajoutées avec succés");
            }
            
        } catch (SQLException ex){
            //JOptionPane.showMessageDialog(null, ex.getMessage(),null, JOptionPane.ERROR_MESSAGE);
            jTextArea1.setText(ex.getMessage());
        }
    }//GEN-LAST:event_btnValiderActionPerformed

    private void btnImprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimerMouseClicked
        carteGrise carte = new carteGrise();
        carte.setVisible(true);
        carte.setAlwaysOnTop(true);
    }//GEN-LAST:event_btnImprimerMouseClicked

    private void btnFermerANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFermerANActionPerformed

    private void btnFermerANMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFermerANMouseClicked
        this.dispose(); 
        
    }//GEN-LAST:event_btnFermerANMouseClicked

    private void btnFermerANMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFermerANMouseEntered
        btnFermerAN.setBackground(Color.red);
        btnFermerAN.setForeground(Color.white);
    }//GEN-LAST:event_btnFermerANMouseEntered

    private void btnFermerANMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFermerANMouseExited
        btnFermerAN.setBackground(new Color(240,240,240));
        btnFermerAN.setForeground(Color.black);
    }//GEN-LAST:event_btnFermerANMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(assuranceNouvelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new assuranceNouvelle().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFermerAN;
    private javax.swing.JButton btnImprimer;
    private javax.swing.JButton btnValider;
    private javax.swing.JButton btnValider1;
    private javax.swing.JComboBox<String> cboCategorie;
    private javax.swing.JComboBox<String> cboEnergie;
    private javax.swing.JComboBox<String> cboGroupe;
    private javax.swing.JComboBox<String> cboTalon;
    private javax.swing.JComboBox<String> cboTonnage;
    private com.toedter.calendar.JDateChooser dateDelivrance;
    private com.toedter.calendar.JDateChooser dateEcheance;
    private com.toedter.calendar.JDateChooser dateRappel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel labelHeure;
    private com.toedter.components.JSpinField nombreChevaux;
    private com.toedter.components.JSpinField nombreMois;
    private com.toedter.components.JSpinField nombrePlaces;
    private javax.swing.JTextField txtAdresse;
    public static javax.swing.JTextField txtAssure;
    private javax.swing.JTextField txtAttest;
    private javax.swing.JTextField txtCoutPolice;
    private javax.swing.JTextField txtFG;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtImmat;
    private javax.swing.JTextField txtMarque;
    private javax.swing.JTextField txtPT;
    private javax.swing.JTextField txtPolice;
    private javax.swing.JTextField txtPrimeNette;
    private javax.swing.JTextField txtProfession;
    private javax.swing.JTextField txtRC;
    private javax.swing.JTextField txtSommeEncaisse;
    private javax.swing.JTextField txtSommeFacture;
    private javax.swing.JTextField txtTaxe;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtVehicule;
    // End of variables declaration//GEN-END:variables
}
